<script setup lang="ts">
useSeoMeta({ title: 'Photographe Mariage Mouscron | Safia Moments de Vie', description: 'Photographe de mariage à Mouscron et alentours. Un reportage élégant, naturel et sensible pour raconter votre journée avec authenticité.', ogImage: '/images/galery/mariage11.jpg' })
const faq = [
  { q: 'Comment obtenir un tarif pour notre mariage ?', a: 'Envoyez votre date, votre lieu et les moments que vous souhaitez faire photographier. Safia pourra vous proposer un accompagnement adapté à votre journée.' },
  { q: 'Jusqu’où vous déplacez-vous ?', a: 'Safia est basée à Mouscron et peut se déplacer selon votre projet. Indiquez le lieu du mariage dans votre demande pour obtenir une proposition précise.' },
  { q: 'Comment savoir si votre style nous correspond ?', a: 'Le portfolio présente une approche naturelle, sensible et centrée sur les émotions, les gestes et les détails de la journée.' },
  { q: 'Comment réserver notre date ?', a: 'Commencez par envoyer la date, le lieu et quelques informations sur votre mariage. Safia pourra ensuite confirmer sa disponibilité.' }
]
</script>
<template>
<main class="landing">
  <section class="hero-ad"><div class="copy"><span>Photographe mariage · Mouscron & déplacements</span><h1>Vous vivrez cette journée une fois.</h1><em>Vos images vous la feront revivre.</em><p>Un reportage discret, sensible et vivant pour raconter les émotions, les détails et tous ces instants que vous n’aurez peut-être même pas vus.</p><NuxtLink to="/contact?projet=mariage" class="btn">Vérifier ma date →</NuxtLink><small>♡ Approche naturelle &nbsp; ♡ Reportage sur mesure &nbsp; ♡ Échange personnalisé</small></div><div class="photo"><img src="/images/galery/mariage11.jpg" alt="Photographe mariage Safia Moments de Vie"></div></section>
  <section class="three"><article><b>01</b><h2>Les émotions</h2><p>Les regards, les rires et les gestes spontanés qui rendent votre journée réellement unique.</p></article><article><b>02</b><h2>Les détails</h2><p>Tout ce que vous avez imaginé pendant des mois et que vous voudrez retrouver dans votre récit.</p></article><article><b>03</b><h2>Votre histoire</h2><p>Une galerie cohérente qui ressemble à votre mariage, pas à une succession de poses.</p></article></section>
  <section class="split"><img src="/images/galery/mariage6.jpg" alt="Reportage mariage naturel"><div><span>Présente sans prendre toute la place</span><h2>Profitez. Je raconte.</h2><p>Vous n’avez pas à passer votre mariage devant l’objectif. Safia privilégie une présence discrète et vous guide seulement lorsque c’est utile.</p><NuxtLink to="/portfolio">Voir les mariages →</NuxtLink></div></section>
  <section class="faq"><span>Questions fréquentes</span><h2>Préparer votre reportage</h2><details v-for="item in faq" :key="item.q"><summary>{{ item.q }} <b>+</b></summary><p>{{ item.a }}</p></details></section>
  <section class="final"><span>Votre date est peut-être encore disponible</span><h2>Racontez-moi votre mariage.</h2><p>Envoyez votre date, votre lieu et quelques mots sur la journée que vous imaginez.</p><NuxtLink to="/contact?projet=mariage" class="btn">Vérifier ma date →</NuxtLink></section>
</main>
</template>
<style scoped>
.landing{background:var(--cream)}.hero-ad{min-height:92vh;padding:9rem max(1.5rem,8vw) 5rem;display:grid;grid-template-columns:1fr .9fr;gap:6vw;align-items:center;background:url('/images/bg-hero.png') center/cover}.copy>span,.split span,.faq>span,.final>span{font-size:.6rem;letter-spacing:.25em;text-transform:uppercase;color:var(--accent-dark)}h1,h2{font-family:var(--font-display);font-weight:400;line-height:1.08}h1{font-size:clamp(3rem,5.6vw,5.7rem);margin:.8rem 0;max-width:12ch}.copy em{display:block;font-family:var(--font-script);font-size:clamp(1.6rem,2.6vw,2.4rem);font-style:normal;color:var(--accent-dark)}p{color:var(--text-light);font-size:.84rem;line-height:1.85}.copy p{max-width:52ch;margin:1.4rem 0}.btn{display:inline-flex;background:var(--accent);color:#fff;padding:.9rem 1.4rem;font-size:.62rem;letter-spacing:.16em;text-transform:uppercase}.copy small{display:block;margin-top:1.4rem;color:var(--text-light)}.photo{height:68vh;overflow:hidden;border-radius:48% 48% 0 0/14% 14% 0 0}.photo img,.split img{width:100%;height:100%;object-fit:cover}.three{display:grid;grid-template-columns:repeat(3,1fr);padding:5rem max(1.5rem,8vw);gap:1px;background:var(--cream-dark)}.three article{background:var(--cream);padding:2.5rem}.three b{font-size:.6rem;color:var(--accent-dark)}.three h2{font-size:1.8rem;margin:.6rem 0}.split{display:grid;grid-template-columns:.9fr 1fr;gap:7vw;align-items:center;padding:6rem max(1.5rem,10vw);background:#fff}.split img{height:520px}.split h2,.faq h2,.final h2{font-size:clamp(2rem,4vw,3.7rem);margin:.7rem 0 1.3rem}.split a{display:inline-block;margin-top:1.4rem;border-bottom:1px solid var(--accent-dark);font-size:.63rem;letter-spacing:.14em;text-transform:uppercase}.faq{max-width:850px;margin:auto;padding:6rem 1.5rem}.faq details{border-bottom:1px solid var(--cream-dark)}.faq summary{list-style:none;display:flex;justify-content:space-between;padding:1.4rem 0;cursor:pointer;font-family:var(--font-display)}.faq summary::-webkit-details-marker{display:none}.faq details p{padding:0 2rem 1.4rem 0}.final{text-align:center;background:var(--dark);color:#fff;padding:6rem 1.5rem}.final p{color:rgba(255,255,255,.65);max-width:560px;margin:0 auto 1.7rem}@media(max-width:800px){.hero-ad,.split{grid-template-columns:1fr}.hero-ad{padding-top:7rem}.photo{height:55vh}.three{grid-template-columns:1fr}.split img{height:420px}}
</style>