<script setup lang="ts">
useSeoMeta({ title: 'Formation Photo Personnalisée | Safia Moments de Vie', description: 'Formation photo ciblée et personnalisée avec Safia. Expliquez votre objectif et votre niveau pour recevoir une proposition adaptée.' })
const faq = [
 { q: 'À qui s’adresse cette formation ?', a: 'Aux personnes qui souhaitent travailler un objectif photo précis avec un accompagnement adapté à leur niveau.' },
 { q: 'Comment est défini le format ?', a: 'Safia étudie votre niveau, votre matériel et votre objectif avant de vous proposer le format adapté.' },
 { q: 'Quels sujets peut-on travailler ?', a: 'Technique de prise de vue, boîtier, lumière, composition, cohérence visuelle, retouche ou une problématique précise.' },
 { q: 'Comment faire une demande ?', a: 'Décrivez votre niveau, votre matériel et ce que vous souhaitez réussir à faire. Safia pourra ensuite étudier votre besoin.' }
]
</script>
<template>
<main class="training-page">
<section class="training-hero"><div><span>Formation photo personnalisée</span><h1>Une formation construite autour de votre objectif.</h1><em>Travaillez exactement ce dont vous avez besoin.</em><p>Vous expliquez votre niveau, votre matériel et le résultat que vous voulez atteindre. Safia étudie votre demande et construit un accompagnement ciblé.</p><NuxtLink to="/contact?projet=formation-photo" class="cta">Décrire mon objectif →</NuxtLink><small>♡ Besoin étudié &nbsp; ♡ Accompagnement personnalisé &nbsp; ♡ Proposition adaptée</small></div><figure><img src="/images/galery/entrepreneur6.jpg" alt="Formation photo personnalisée avec Safia"></figure></section>
<section class="needs"><span>Votre point de départ</span><h2>Qu’est-ce que vous voulez enfin maîtriser ?</h2><div><i>Mon boîtier</i><i>La lumière</i><i>La composition</i><i>La retouche</i><i>La cohérence de mes images</i><i>Un besoin spécifique</i></div></section>
<section class="process"><article><b>01</b><h2>Vous expliquez</h2><p>Votre niveau actuel, votre matériel, votre difficulté et le résultat recherché.</p></article><article><b>02</b><h2>Safia analyse</h2><p>La demande est étudiée afin d’identifier les points réellement utiles à travailler.</p></article><article><b>03</b><h2>Vous avancez</h2><p>Vous recevez une proposition d’accompagnement cohérente avec votre objectif.</p></article></section>
<section class="training-split"><img src="/images/galery/entrepreneur10.jpg" alt="Accompagnement photographie"><div><span>Un accompagnement concret</span><h2>Comprendre. Pratiquer. Progresser.</h2><p>L’objectif est de comprendre ce qui vous empêche d’avancer et de vous transmettre des repères que vous pourrez réutiliser ensuite dans votre pratique.</p><NuxtLink to="/contact?projet=formation-photo">Faire analyser mon besoin →</NuxtLink></div></section>
<section class="training-faq"><span>Questions fréquentes</span><h2>Avant votre demande</h2><details v-for="item in faq" :key="item.q"><summary>{{ item.q }} <b>+</b></summary><p>{{ item.a }}</p></details></section>
<section class="training-final"><span>Votre besoin est unique</span><h2>Expliquez votre objectif à Safia.</h2><p>Quelques lignes sur votre niveau, votre matériel et ce que vous souhaitez apprendre suffisent pour commencer.</p><NuxtLink to="/contact?projet=formation-photo" class="cta">Décrire mon besoin →</NuxtLink></section>
</main>
</template>
<style scoped>
.training-page{background:var(--cream)}.training-hero{min-height:92vh;padding:9rem max(1.5rem,8vw) 5rem;display:grid;grid-template-columns:1.05fr .8fr;gap:6vw;align-items:center;background:url('/images/bg-hero.png') center/cover}.training-hero span,.needs>span,.training-split span,.training-faq>span,.training-final>span{font-size:.6rem;letter-spacing:.25em;text-transform:uppercase;color:var(--accent-dark)}h1,h2{font-family:var(--font-display);font-weight:400;line-height:1.08}h1{font-size:clamp(2.8rem,5.2vw,5.4rem);margin:.8rem 0;max-width:14ch}.training-hero em{display:block;font-family:var(--font-script);font-size:clamp(1.5rem,2.5vw,2.3rem);font-style:normal;color:var(--accent-dark)}p{color:var(--text-light);font-size:.84rem;line-height:1.85}.training-hero p{max-width:55ch;margin:1.4rem 0}.cta{display:inline-flex;background:var(--accent);color:#fff;padding:.9rem 1.4rem;font-size:.62rem;letter-spacing:.16em;text-transform:uppercase}.training-hero small{display:block;margin-top:1.4rem;color:var(--text-light)}.training-hero figure{height:66vh;overflow:hidden;border-radius:48% 48% 0 0/14% 14% 0 0}.training-hero img,.training-split img{width:100%;height:100%;object-fit:cover}.needs{text-align:center;padding:6rem 1.5rem;background:#fff}.needs h2,.training-split h2,.training-faq h2,.training-final h2{font-size:clamp(2rem,4vw,3.7rem);margin:.8rem 0 2rem}.needs div{display:flex;justify-content:center;flex-wrap:wrap;gap:.7rem;max-width:850px;margin:auto}.needs i{font-style:normal;border:1px solid var(--cream-dark);padding:.75rem 1rem;font-size:.72rem;color:var(--text-light);background:var(--cream)}.process{display:grid;grid-template-columns:repeat(3,1fr);padding:5rem max(1.5rem,8vw);gap:1px;background:var(--cream-dark)}.process article{background:var(--cream);padding:2.5rem}.process b{font-size:.6rem;color:var(--accent-dark)}.process h2{font-size:1.7rem;margin:.6rem 0}.training-split{display:grid;grid-template-columns:.9fr 1fr;gap:7vw;align-items:center;padding:6rem max(1.5rem,10vw);background:#fff}.training-split img{height:520px}.training-split a{display:inline-block;margin-top:1.4rem;border-bottom:1px solid var(--accent-dark);font-size:.63rem;letter-spacing:.14em;text-transform:uppercase}.training-faq{max-width:850px;margin:auto;padding:6rem 1.5rem}.training-faq details{border-bottom:1px solid var(--cream-dark)}.training-faq summary{list-style:none;display:flex;justify-content:space-between;padding:1.4rem 0;cursor:pointer;font-family:var(--font-display)}.training-faq summary::-webkit-details-marker{display:none}.training-faq details p{padding:0 2rem 1.4rem 0}.training-final{text-align:center;background:var(--dark);color:#fff;padding:6rem 1.5rem}.training-final p{color:rgba(255,255,255,.65);max-width:620px;margin:0 auto 1.7rem}@media(max-width:800px){.training-hero,.training-split{grid-template-columns:1fr}.training-hero{padding-top:7rem}.training-hero figure{height:55vh}.process{grid-template-columns:1fr}.training-split img{height:420px}}
</style>